### ISSUE TITLE
TypeError: normal() received an invalid combination of arguments - got (means=Tensor, std=float, ), 

### ISSUE THREAD

**Issue by hyeseonko** [jakezhaojb/ARAE#19]
Hi, when I run run_snli.py, it does not work. :'(

>> python run_snli.py --data_path ./data/snli_lm --no_earlystopping

then..I encountered the TypeError as below. Do you know any solutions?

Traceback (most recent call last):
  File "run_snli.py", line 103, in <module>
    exec(open("train.py").read())
  File "<string>", line 434, in <module>
  File "<string>", line 389, in train
  File "<string>", line 247, in train_ae
  File "C:\Users\hsko0\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Generation\ARAE\lang\models.py", line 174, in forward
    hidden = self.encode(indices, lengths, noise)
  File "D:\Generation\ARAE\lang\models.py", line 199, in encode
    std=self.noise_r)
TypeError: normal() received an invalid combination of arguments - got (means=Tensor, std=float, ), but expected one of:
 * (Tensor mean, Tensor std, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, torch.Generator generator, Tensor out)

**Comment by jasonyu1996** [comment]
It's an API change of pytorch. means has been changed into mean
